version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: wtf-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  sensor:
    build:
      context: .
      dockerfile: Dockerfile.sensor
    container_name: wtf-sensor
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - LOG_LEVEL=INFO
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  detector:
    build:
      context: .
      dockerfile: Dockerfile.detector
    container_name: wtf-detector
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - LOG_LEVEL=INFO
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  ollama:
    image: ollama/ollama:latest
    container_name: wtf-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD-SHELL", "ollama list || exit 1"] 
      interval: 30s
      timeout: 20s
      retries: 10
      start_period: 60s

  ollama-init:
    build:
      context: .
      dockerfile: Dockerfile.ollama-init
    depends_on:
      ollama:
        condition: service_healthy
    container_name: wtf-ollama-init
    restart: "no"

  llm:
    build:
      context: .
      dockerfile: Dockerfile.llm
    container_name: wtf-llm
    depends_on:
      redis:
        condition: service_healthy
      ollama:
        condition: service_healthy
    environment:
      - LOG_LEVEL=INFO
      - OLLAMA_HOST=http://ollama:11434
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    # Allocate more resources for LLM
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: wtf-api
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - LOG_LEVEL=INFO
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
volumes:
  redis_data:
  ollama_data: